name: CI/CD for Wisecow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Build and push Docker image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/wisecow:latest
            ${{ secrets.DOCKER_USERNAME }}/wisecow:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      # Checkout repo again (for manifests)
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up kubectl
      - name: Set up Kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.33.1'

      # Start Minikube (inside GitHub runner)
      - name: Start Minikube
        uses: medyagh/setup-minikube@latest

      # Install cert-manager
      - name: Install cert-manager
        run: |
          kubectl apply --validate=false -f https://github.com/cert-manager/cert-manager/releases/latest/download/cert-manager.yaml
          kubectl -n cert-manager rollout status deploy/cert-manager
          kubectl -n cert-manager rollout status deploy/cert-manager-webhook
          kubectl -n cert-manager rollout status deploy/cert-manager-cainjector

      # Apply ClusterIssuer (self-signed)
      - name: Apply ClusterIssuer
        run: |
          kubectl apply -f clusterissuer-selfsigned.yaml

      # Deploy Wisecow app + service
      - name: Deploy Wisecow
        run: |
          kubectl apply -f wisecow-deployment.yaml
          kubectl apply -f wisecow-service.yaml

      # Apply Certificate
      - name: Apply Certificate
        run: |
          kubectl apply -f certificate-wisecow.yaml

      # Apply Ingress
      - name: Apply Ingress
        run: |
          kubectl apply -f wisecow-ingress.yaml

      # Verify TLS + rollout
      - name: Verify rollout & TLS
        run: |
          kubectl rollout status deployment/wisecow-deployment
          kubectl get certificate wisecow-tls -o yaml
          kubectl describe ingress wisecow-ingress
